### PR TITLE
Standalone Qube icons

### PR DESCRIPTION
**Pull request by Narvey**
First stage of fixing https://github.com/QubesOS/qubes-issues/issues/6745
Please label with hacktoberfest-accepted unless there is some reason this PR shouldn't [qualify](https://hacktoberfest.com/participation/#pr-mr-details) (in which case let me know so I can improve!)

### CODE REVIEW

**Comment by marmarta** [comment]
Oh I like them! One question: how do they perform visibility-wise with light and dark themes? I worry a bit that the border might be too thin to be noticeable with dark system theme (e.g. in the menu). Do you have any screenshots?

**Comment by marmarek** [comment]
You need to add the files to packages (spec file for rpm, debian/install etc) - see CI logs at https://gitlab.com/QubesOS/qubes-artwork/-/pipelines/679296283

**Comment by Narvey** [comment]
I'm sorry, I'm very new to this. How would I go about doing that? There were no informative error messages (let alone instructions) at the link you provided.
Also it looks like I might need to sign them? Does it matter which key I use?

**Comment by marmarek** [comment]
See how other files are listed in https://github.com/QubesOS/qubes-artwork/blob/master/qubes-artwork.spec.in and https://github.com/QubesOS/qubes-artwork/blob/master/debian/install

**Comment by marmarta** [comment]
The guide to code signing is here: https://www.qubes-os.org/doc/code-signing/ ; you need to use your own key, this is the crucial thing, but if you use already-existing one or a newly generated is upt o you.

**Pull request merged**
