### PR TITLE
Qubes outline logo for Plymouth shutdown splash

### LINKED ISSUE #5728: Shut-down Animation confusing
As a new Qubes user who did not come into Qubes from Linux environments, it is confusing to me that the GUI things the machine does to shut-down, are identical to what I see the GUI doing upon boot. 

CAVEAT: This is a profoundly low priority "issue," in my mind—but is something I wanted to get onto the radar of things, should committing to making Qubes a more comfortable experience for non-Linux users, be elevated as a priority. If enough of these issues pile-up making an Epic for "Make Qubes mainstream friendly" shd maybe happen... but until then, ohai—just gonna leave this here.

### PR DESCRIPTION
**Pull request by alimirjamali**
fixes: https://github.com/QubesOS/qubes-issues/issues/5728

### CODE REVIEW

**Comment by marmarek** [comment]
Sorry about offtopic, but on the topic of Plymouth, there is an annoying Plymouth bug that maybe you can help with: https://gitlab.freedesktop.org/plymouth/plymouth/-/issues/205. It's a minor issue, but it affects our openQA setup and is the reason for most of the "softfail" states.

**Comment by alimirjamali** [comment]
> Sorry about offtopic, but on the topic of Plymouth, there is an annoying Plymouth bug that maybe you can help with

Sure. I will be more than glad to help. I will look into it and see if I can find the issue. And I will also try to make the boring boot selection menu a little bit more modern. Something similar to Ubuntu menu or openSUSE menu

**Comment by marmarek** [comment]
> And I will also try to make the boring boot selection menu a little bit more modern

Be aware of the reason why it's this way now: https://github.com/qubesos/qubes-issues/issues/8464

**Comment by alimirjamali** [comment]
> Sorry about offtopic, but on the topic of Plymouth, there is an annoying Plymouth bug that maybe you can help with: https://gitlab.freedesktop.org/plymouth/plymouth/-/issues/205. It's a minor issue, but it affects our openQA setup and is the reason for most of the "softfail" states.

I am still looking at the above issue and other potential improvements to `qubes-dark` Plymouth theme. Just on side-note, I wanted to implement Caps-lock indicator for LUKS passphrase dialog. Turns out that the Plymouth version on Fedora 37 is 22.02.122 and it does not include this fix:

https://gitlab.freedesktop.org/plymouth/plymouth/-/commit/3e6d59cbd915836b209100c72e3173637af54886

So no Caps-lock indicator for the time as back-porting is not worth it. BTW, The script needs some mild refactoring. For example setting the logo position in `refresh_callbak` function 50 times per second is unnecessary. I have to hookup an external monitor to my laptop to deeply analyze the original bug you mentioned earlier.

**Comment by alimirjamali** [comment]
> there is an annoying Plymouth bug that maybe you can help with: https://gitlab.freedesktop.org/plymouth/plymouth/-/issues/205. It's a minor issue, but it affects our openQA setup and is the reason for most of the "softfail" states.

Finally received the DisplayPort to HDMI cable few minutes ago. I was not able to work on the above bug since this EliteBook 820 laptop has only DisplayPort and VGA outputs but my monitor has only HDMI. Therefore I had to get the converter cable. Combined with the HDMI capture dongle, it makes it easy to work with.

DisplayPort to HDMI & Capture dongle

Now that I have the necessary hardware, I can reproduce the bug and I see the exact symptom. The LUKS password entry jumps off-screen after pressing ESC key twice (as you mentioned). But it is only the white box that jumps off-screen. I have to see the screen positioning mechanism within the Theme's script. The issue is most probably with the theme's script, with slight chance of being because of the older version of plymouth, or even the latest versions are also affected. This should take some time.

https://github.com/user-attachments/assets/aaaa38f5-e691-438b-b56e-841a81829746

BTW, Here is the video of the shutdown splash with outline logo

https://github.com/user-attachments/assets/75a273b3-9189-45e4-b93a-de5d662d2dd2

**Review by marmarek — APPROVED** [review]

**Pull request merged**
